🟢Question 1

 
Create a CSV file named students.csv with columns Name, Age, and Marks, then read it using Pandas.

In [1]:
import pandas as pd
MK=pd.read_csv("students.csv")
MK.head()

    Name  Age  Marks
0  Madhu   25     90
1  Punam   20     80
2  Rahul   22     85
3   Amit   21     70
4  Priya   23     95

🟢Question 2
 
Display only the Marks column from the DataFrame.

In [2]:
MK["Marks"]

0    90
1    80
2    85
3    70
4    95
Name: Marks, dtype: int64

🟢Question 3

 
Display only the students whose marks are greater than 80.

In [3]:
MK[MK["Marks"]>80]

    Name  Age  Marks
0  Madhu   25     90
2  Rahul   22     85
4  Priya   23     95

🟢Question 4

 
Display students whose marks are greater than or equal to 85.

In [5]:
MK[MK["Marks"]>=85]

    Name  Age  Marks
0  Madhu   25     90
2  Rahul   22     85
4  Priya   23     95

🟢 Question 5


Display students whose Age is greater than 21.

In [6]:
MK[MK["Age"]>21]

    Name  Age  Marks
0  Madhu   25     90
2  Rahul   22     85
4  Priya   23     95

Question 6

 
Display students whose Marks are greater than 80 AND Age is greater than 21.

In [11]:
MK[(MK["Marks"] > 80) & (MK["Age"] > 21)]

    Name  Age  Marks
0  Madhu   25     90
2  Rahul   22     85
4  Priya   23     95

 🟢 Question 7

 
Display students whose Marks are less than 80 OR Age is less than 21.

In [12]:
MK[(MK["Marks"]<80) | ( MK ["Age"] < 21)]

    Name  Age  Marks
1  Punam   20     80
3   Amit   21     70

Question 8

 
Display only the Name and Marks columns for students whose marks are greater than 80.

In [13]:
MK[MK["Marks"] > 80] 
MK[["Name", "Marks"]]

    Name  Marks
0  Madhu     90
1  Punam     80
2  Rahul     85
3   Amit     70
4  Priya     95

Question 9
 
Sort the DataFrame by Marks from highest to lowest.

In [15]:
MK.sort_values("Marks", ascending=True)

    Name  Age  Marks
3   Amit   21     70
1  Punam   20     80
2  Rahul   22     85
0  Madhu   25     90
4  Priya   23     95

In [16]:
MK.sort_values("Marks", ascending=False)

    Name  Age  Marks
4  Priya   23     95
0  Madhu   25     90
2  Rahul   22     85
1  Punam   20     80
3   Amit   21     70

Question 10 — Final Practice

 
Find the student with the highest marks and display their complete row.

In [24]:
MK.sort_values("Marks",ascending =False).iloc[0]

Name     Priya
Age         23
Marks       95
Name: 4, dtype: object

# Day 09 — Pandas CSV & Filtering

## Topics Covered

- Reading CSV files using Pandas
- `pd.read_csv()`
- `head()`
- Column selection
- Boolean filtering
- Multiple conditions
- `&` operator for AND
- `|` operator for OR
- Selecting multiple columns
- Sorting DataFrame using `sort_values()`
- `ascending=False`
- Selecting rows using `iloc[]`

## Practice

- Read `students.csv` using Pandas
- Selected the `Marks` column
- Filtered students based on marks
- Filtered students based on age
- Used multiple conditions with `&`
- Used OR condition with `|`
- Selected specific columns
- Sorted students by marks
- Found the student with the highest marks

## Key Learnings

- `pd.read_csv()` → Reads a CSV file into a DataFrame
- `df["Marks"]` → Selects a column
- `df[df["Marks"] > 80]` → Filters rows
- `&` → AND condition
- `|` → OR condition
- `df.sort_values("Marks", ascending=False)` → Sorts highest to lowest
- `df.iloc[0]` → Selects the first row

## Day 09 Summary

Today I learned how to work with CSV files using Pandas.
I practiced filtering, multiple conditions, column selection,
sorting, and finding the highest-scoring student.