🟢 Question 1

Create the following DataFrame and check which values are missing.

In [4]:
import pandas as pd
data = {
    "Name": ["Madhu", "Punam", "Rahul", "Amit"],
    "Marks": [90, None, 85, None],
    "Age": [25, 20, None, 21]
}
df = pd.DataFrame(data)
df.isnull()

    Name  Marks    Age
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

🟢 Question 2
 
Check how many missing values are present in each column.

In [5]:
df.isnull().sum()

Name     0
Marks    2
Age      1
dtype: int64

🟢 Question 3

Remove all rows that contain missing values.

In [6]:
df.dropna()

    Name  Marks   Age
0  Madhu   90.0  25.0

🟢 Question 4

Fill all missing values in the Marks column with 0.

In [7]:
df["Marks"].fillna(0)

0    90.0
1     0.0
2    85.0
3     0.0
Name: Marks, dtype: float64

🟢 Question 5

Fill the missing values in the Age column with the average age.

In [10]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

🟢 Question 6

Check again whether the DataFrame still contains any missing values.

In [11]:
df.isnull().sum()

Name     0
Marks    2
Age      0
dtype: int64

🟢 Question 7
 
Now permanently replace all missing values in the Marks column with 0.

In [12]:
df["Marks"] = df["Marks"].fillna(0)

🟢 Question 8
 
Create a duplicate row in the DataFrame and then remove the duplicate rows.

In [17]:
df = pd.concat([df, df.iloc[[3]]])
# df=df.drop_duplicates()
df

    Name  Marks   Age
0  Madhu   90.0  25.0
1  Punam    0.0  20.0
2  Rahul   85.0  22.0
3   Amit    0.0  21.0
3   Amit    0.0  21.0

In [18]:
df = df.drop_duplicates()
df

    Name  Marks   Age
0  Madhu   90.0  25.0
1  Punam    0.0  20.0
2  Rahul   85.0  22.0
3   Amit    0.0  21.0

🟢 Question 9

Check whether any duplicate rows are still present in the DataFrame.

In [19]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

🟢 Question 10 — Final Practice
 
Count the total number of missing values in the entire DataFrame.

In [20]:
df.isnull().sum().sum()

np.int64(0)