🟢 Question 1


Create these two DataFrames and merge them using the common Name column.

In [2]:
import pandas as pd
students = pd.DataFrame({
    "Name": ["Madhu", "Punam", "Rahul"],
    "Age": [25, 20, 22]
})

marks = pd.DataFrame({
    "Name": ["Madhu", "Punam", "Rahul"],
    "Marks": [90, 80, 85]
})
pd.merge(students, marks, on="Name")

    Name  Age  Marks
0  Madhu   25     90
1  Punam   20     80
2  Rahul   22     85

🟢 Question 2

 
Sort the merged DataFrame by Age from youngest to oldest.

In [10]:

df = pd.merge(students, marks, on="Name")
df.sort_values("Age", ascending=True)

    Name  Age  Marks
1  Punam   20     80
2  Rahul   22     85
0  Madhu   25     90

🟢 Question 3
 
Sort the DataFrame by Marks from highest to lowest.

In [11]:
df.sort_values("Marks", ascending=False)

    Name  Age  Marks
0  Madhu   25     90
2  Rahul   22     85
1  Punam   20     80

🟢 Question 4

 
Create a second DataFrame containing students' Course information and merge it with the current DataFrame using Name.

In [12]:
course = pd.DataFrame({
    "Name": ["Madhu", "Punam", "Rahul"],
    "Course": ["AI", "Web", "ML"]
})
pd.merge(df, course, on="Name")

    Name  Age  Marks Course
0  Madhu   25     90     AI
1  Punam   20     80    Web
2  Rahul   22     85     ML

🟢 Question 5
 
What happens if we use how="left" while merging?

In [15]:
pd.merge(df, course, on="Name", how="left")

    Name  Age  Marks Course
0  Madhu   25     90     AI
1  Punam   20     80    Web
2  Rahul   22     85     ML

🟢 Question 6
 
Create another DataFrame with one extra student, Amit, and use how="left" to merge it with df.

In [20]:
df = pd.DataFrame({
    "Name": ["Madhu", "Punam", "Rahul", "Amit"],
    "Age": [25, 20, 22, 21],
    "Marks": [90, 80, 85, 70]
})
pd.merge(df, course2, on="Name", how="left")

    Name  Age  Marks        Course
0  Madhu   25     90            AI
1  Punam   20     80           Web
2  Rahul   22     85            ML
3   Amit   21     70  Data Science

In [21]:
df

    Name  Age  Marks
0  Madhu   25     90
1  Punam   20     80
2  Rahul   22     85
3   Amit   21     70

🟢 Question 7
 
Use how="inner" to merge df and course2 using the Name column.

In [23]:
pd.merge(df, course2, on="Name", how="inner")

    Name  Age  Marks        Course
0  Madhu   25     90            AI
1  Punam   20     80           Web
2  Rahul   22     85            ML
3   Amit   21     70  Data Science

🟢 Question 8
  
Use how="outer" to merge df and course2 using the Name column.

In [24]:
pd.merge(df, course2, on="Name", how="outer")

    Name  Age  Marks        Course
0   Amit   21     70  Data Science
1  Madhu   25     90            AI
2  Punam   20     80           Web
3  Rahul   22     85            ML

🟢 Question 9

 
Sort the merged DataFrame by Marks from lowest to highest.

In [25]:
result = pd.merge(df, course2, on="Name", how="outer")

result.sort_values("Marks", ascending=True)

    Name  Age  Marks        Course
0   Amit   21     70  Data Science
2  Punam   20     80           Web
3  Rahul   22     85            ML
1  Madhu   25     90            AI

🟢 Question 10 — Final

 
After merging df and course2, display only the students who have Marks greater than 80.

In [26]:
result = pd.merge(df, course2, on="Name", how="inner")
result[result["Marks"] > 80]

    Name  Age  Marks Course
0  Madhu   25     90     AI
2  Rahul   22     85     ML